### ISSUE TITLE
CSV parser fails when trying to import XLSX

### ISSUE THREAD

**Issue by funkybob** [jazzband/tablib#108]
Using 0.9.11 I get the following trying to import a XLSX file...

```
Traceback (most recent call last):
File "...", line 81, in parse
self.source_data = tablib.import_set(source)
File ".../site-packages/tablib/core.py", line 1006, in import_set
format.import_set(data, stream)
File ".../site-packages/tablib/formats/_csv.py", line 41, in import_set
for i, row in enumerate(rows):
File ".../site-packages/tablib/packages/unicodecsv/__init__.py", line 54, in next
row = self.reader.next()
Error: line contains NULL byte
```

**Comment by claudep** [comment]
I cannot say I solve all issues, but tablib should be a little more robust now wrt autodetection. Feel free to open new tickets if you can reproduce crashes on master.
