### ISSUE TITLE
Exception: Unexpected data type <class 'bytes'>

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/tablib#159]
Hi Guys, i have an error when i try export all news in django admin:

Traceback (most recent call last):

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, _callback_args, *_callback_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/contrib/admin/options.py", line 432, in wrapper
return self.admin_site.admin_view(view)(_args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/utils/decorators.py", line 99, in _wrapped_view
response = view_func(request, _args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/views/decorators/cache.py", line 52, in _wrapped_view_func
response = view_func(request, _args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/contrib/admin/sites.py", line 198, in inner
return view(request, _args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/utils/decorators.py", line 29, in _wrapper
return bound_func(_args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/utils/decorators.py", line 99, in _wrapped_view
response = view_func(request, _args, *_kwargs)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/utils/decorators.py", line 25, in bound_func
return func(self, _args2, *_kwargs2)

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/contrib/admin/options.py", line 1347, in changelist_view
response = self.response_action(request, queryset=cl.get_queryset(request))

File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/contrib/admin/options.py", line 1084, in response_action
response = func(self, request, queryset)

File "/home/salahaddinal/webapps/tiempoturco/tiempoturco/actions.py", line 60, in export_as_excel
response.write(data.xls)

File "/home/salahaddinal/lib/python3.4/tablib-0.10.0-py3.4.egg/tablib/formats/_xls.py", line 44, in export_set
dset_sheet(dataset, ws)

File "/home/salahaddinal/lib/python3.4/tablib-0.10.0-py3.4.egg/tablib/formats/_xls.py", line 116, in dset_sheet
ws.write(i, j, col, bold)

File "/home/salahaddinal/lib/python3.4/tablib-0.10.0-py3.4.egg/tablib/packages/xlwt3/Worksheet.py", line 1002, in write
self.row(r).write(c, label, style)

File "/home/salahaddinal/lib/python3.4/tablib-0.10.0-py3.4.egg/tablib/packages/xlwt3/Row.py", line 248, in write
raise Exception("Unexpected data type %r" % type(label))

Exception: Unexpected data type <class 'bytes'>

I´m working with Django 1.6.5, Python 3.4 and last version of tab lib.

Can anyone explain me this?

**Comment by claudep** [comment]
Looks like more as a support issue.
