### ISSUE TITLE
import_set not working under Python 3.4.10 with xlsx files

### ISSUE THREAD

**Issue by unsignedzero** [jazzband/tablib#203]
I'm currently testing my code in a virtualenv using Python3. It works just fine when I run it under Python2 but when I open an xlsx using tablet.import_set using Pythong3, I get this stack error below. 

```python
python3
[unsignedzero 02:07:45]> import tablib
[unsignedzero 02:07:47]> tablib.import_set("temp_test_output.xlsx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/core.py", line 1005, in import_set
    (format, stream) = detect(stream)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/core.py", line 996, in detect
    if fmt.detect(stream):
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/formats/_xlsx.py", line 31, in detect
    openpyxl.reader.excel.load_workbook(stream)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/excel.py", line 85, in load_workbook
    raise e
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/excel.py", line 81, in load_workbook
    _load_workbook(wb, archive, filename, use_iterators)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/excel.py", line 114, in _load_workbook
    new_ws = read_worksheet(archive.read(worksheet_path), wb, sheet_name, string_table, style_table)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/worksheet.py", line 116, in read_worksheet
    fast_parse(ws, xml_source, string_table, style_table)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/worksheet.py", line 81, in fast_parse
    source = _get_xml_iter(xml_source)
  File "/home/unsignedzero/.local/py_env/lib/python3.4/site-packages/tablib/packages/openpyxl3/reader/worksheet.py", line 43, in _get_xml_iter
    return StringIO(xml_source)
TypeError: initial_value must be str or None, not bytes
```

This looks to be a bug using the xml reader?

**Comment by unsignedzero** [comment]
Seems like I had a buggy pip install and it work just fine, don't know what happened but at least it's fixed.

**Comment by unsignedzero** [comment]
Problem still persists.... ... Had a fluke and though it was fixed.

**Comment by jmaupetit** [comment]
Same troubles here. Did you found a solution?

**Comment by tadeo** [comment]
I'm getting the same exception under Python 3 importing a CSV file. I think a clue about how to solve it in this [StackOverflow anwer](https://stackoverflow.com/a/31067445/2055202)

**Comment by claudep** [comment]
`import_set` requires a stream input, not a path string.
https://tablib.readthedocs.io/en/stable/api/#tablib.import_set

I plan to suggest a patch to allow paths and file-like objects in input, but this is not the subject of this issue.

**Comment by Ken4scholars** [comment]
@claudep actually, the problem persists even with stream input or rather the problem is as a result of the byte stream input. If you check the StackOverflow question linked by @tadeo you will see that the issue is that `StringIO` expects a `str` object in Python 3 and not a byte object. So when a byte stream is passed, it fails. The Python docs suggest using the io module in Python 3

**Comment by claudep** [comment]
Are you able to reproduce the issue with a recent version? Did you try with master code?

**Comment by Ken4scholars** [comment]
@claudep I reproduced with version 0.12.1

**Comment by claudep** [comment]
Please try with the latest, 0.14.0
