### ISSUE TITLE
Support importing ragged CSV text into a Dataset

### ISSUE THREAD

**Issue by klothe** [jazzband/tablib#226]
Right now Dataset._validate prevents importing data where not all rows have the same width. This is not possible in some formats but is common in CSV files. Example:

``` python
from tablib import Dataset
from tablib.formats import csv
ds = Dataset()
csv.import_set(ds, "a,b,c\nx,y")
```

The result is:

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tablib/formats/_csv.py", line 48, in import_set
    dset.append(row)
  File "/usr/local/lib/python2.7/site-packages/tablib/core.py", line 668, in append
    self.rpush(row, tags)
  File "/usr/local/lib/python2.7/site-packages/tablib/core.py", line 652, in rpush
    self.insert(self.height, row=row, tags=tags)
  File "/usr/local/lib/python2.7/site-packages/tablib/core.py", line 643, in insert
    self._validate(row)
  File "/usr/local/lib/python2.7/site-packages/tablib/core.py", line 283, in _validate
    raise InvalidDimensions
tablib.core.InvalidDimensions
```

It may not be a good idea to actually represent ragged data in a Dataset, but it should be possible to import ragged CSV text into a uniform-width Dataset by filling in empty elements to make all rows match the width of the widest row.

**Comment by klothe** [comment]
See #227

**Comment by kennethreitz** [comment]
I'm torn about this. We could make it possible to provide `None' as a value for extra values, but I'd like to think that this type of data simply doesn't belong with this library.

**Comment by klothe** [comment]
I've been using this feature to import rectangular data sets from CSV files where separator characters for trailing blank cells are omitted. In particular, [Tabula](https://github.com/tabulapdf/tabula) outputs CSV files like this when extracting tables from PDFs.

I agree that Tablib shouldn't be used for working with ragged data sets, but these are more like rectangular data sets with variant formatting (because columns are meaningful), so filling in extra blank cells is the right behavior. I found it easier to handle that inside Tabilb than to pre-process the files before importing them to get around the InvalidDimensions error.

**Comment by dcfix** [comment]
Isn't a ragged CSV file really just a rectangular data set with some primitive compression applied?

**Comment by brihuega** [comment]
This issue still raises when the first row is shorter.

`import tablib
ds = tablib.import_set("a,b\nx,y,z", format='csv', headers=False)`

`Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 942, in import_set
    return Dataset().load(normalize_input(stream), format, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 421, in load
    fmt.import_set(self, stream, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/tablib/formats/_csv.py", line 52, in import_set
    dset.append(row)
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 479, in append
    self.rpush(row, tags)
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 465, in rpush
    self.insert(self.height, row=row, tags=tags)
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 453, in insert
    self._validate(row)
  File "/usr/local/lib/python3.12/site-packages/tablib/core.py", line 267, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions`

It raises also with headers=True

It whould be great to avoid pre-processing the files.
Thanks
