### ISSUE TITLE
Possible incompatibility with openpyxl>=2.6 during export

### ISSUE THREAD

**Issue by pgcd** [jazzband/tablib#375]
```
Traceback (most recent call last):
 [..snip...]
  File "/home/user/venv/src/tablib/tablib/formats/_xlsx.py", line 43, in export_set
    dset_sheet(dataset, ws, freeze_panes=freeze_panes)
  File "/home/user/venv/src/tablib/tablib/formats/_xlsx.py", line 145, in dset_sheet
    cell.value = unicode(col)
  File "/home/user/venv/lib/python3.6/site-packages/openpyxl/cell/cell.py", line 252, in value
    self._bind_value(value)
  File "/home/user/venv/lib/python3.6/site-packages/openpyxl/cell/cell.py", line 218, in _bind_value
    raise ValueError("Cannot convert {0!r} to Excel".format(value))
ValueError: Cannot convert 'random string value' to Excel 
```
As far as I can tell, this happens with any string value in any position, and it's definitely caused by openpyxl>=2.6 (reverting to 2.5.14 fixed it for me).

**Comment by claudep** [comment]
The CI server is currently using openpyxl-2.6.4. Do you think it could be an untested path? Please provide a reproducible case with sample data.

**Comment by claudep** [comment]
I'm closing it for now, but do not hesitate to reopen if you can give us a reproducible case.
