### ISSUE TITLE
_csv.Error: iterator should return strings, not bytes

### ISSUE THREAD

**Issue by forhot2000** [jazzband/tablib#423]
when I use load method to load data from csv file, it throws `_csv.Error: iterator should return strings, not bytes`

```python
with open(path, "r") as csv_file:
    data = Dataset().load(csv_file.read())
    print(data)
    csv_file.close()
```

result:

```log
Traceback (most recent call last):
  File "tmp/tablib_test.py", line 25, in <module>
    data = Dataset().load(csv_file.read())
  File "/Users/wangxiang/work/mammoth/touchparse-py/venv/lib/python2.7/site-packages/tablib/core.py", line 433, in load
    import_set(self, in_stream, **kwargs)
  File "/Users/wangxiang/work/mammoth/touchparse-py/venv/lib/python2.7/site-packages/tablib/formats/_csv.py", line 45, in import_set
    for i, row in enumerate(rows):
  File "/Users/wangxiang/work/mammoth/touchparse-py/venv/lib/python2.7/site-packages/backports/csv.py", line 409, in __next__
    raise Error(err_str.format(typ_name))
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

I have searched from stackoverflow, there is a doc for this issue, but it not works for me, python 2.7 don't have encoding parameter for open method

https://stackoverflow.com/questions/8515053/csv-error-iterator-should-return-strings-not-bytes

> ```python
> ifile  = open('sample.csv', "rt", encoding=<theencodingofthefile>)
> ```

but, I have tried to load data by build-in csv module, it works fine:

```python
with open(path, 'r') as csv_file:
    read = csv.reader(csv_file)
    for row in read:
        print (row)
    csv_file.close()
```

result:

```
['name', 'age']
['bob', '21']
['tom', '35']
['john', '28']
```

I have to copy codes from load method, and modify it as this:

```python
with open(path, 'r') as csv_file:
    data = Dataset()
    read = csv.reader(csv_file)
    for i, row in enumerate(read):
        if (i == 0) and (data.headers):
            data.headers = row
        elif row:
            data.append(row)
    print(data.csv)
    csv_file.close()
```

is there any better way to do it?

**Comment by claudep** [comment]
I'm very sorry, but we've stopped supporting Python 2.7, as it is very soon end-of-life. Thanks anyway for the detailed report.
