### ISSUE TITLE
tablib==0.14.0 creates error in Django project

### ISSUE THREAD

**Issue by kegan** [jazzband/tablib#434]
I have a Django project that use [django-import-export](https://github.com/django-import-export/django-import-export) which in turn uses `tablib`.

After some upgrades (`pip-compile -U` follow by `pip-sync`), I am getting issue with `Django (2.2.7)`.

```
$ ./manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/-redacted-/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/-redacted-/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/contrib/admin/checks.py", line 79, in check_dependencies
    for engine in engines.all():
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/Users/-redacted-/.pyenv/versions/3.6.4/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 12, in <module>
    from rest_framework.renderers import HTMLFormRenderer
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/rest_framework/renderers.py", line 19, in <module>
    from django.test.client import encode_multipart
  File "/Users/-redacted-/.pyenv/versions/-redacted-/lib/python3.6/site-packages/django/test/client.py", line 23, in <module>
    from django.test import signals
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('django.test.signals') at 4583373176
```

I have managed to narrow down the issue, which is due to the missing `backports.csv==1.0.7` dependency is missing which `pip-compile` generate dependency for `tablib==0.14.0`.

If I manually install the `backports.csv`, then everything is working again.

I am not sure if the omission of `backports.csv` was on purpose for `tablib==0.14.0` or was it a bug. Or maybe this bug report should be with `django-import-export`? 😅 

Thank you.

**Comment by claudep** [comment]
`backports.csv` is only useful on Python 2, that's why it is not installed on Python 3 (setup.py is using a conditional dependency). I don't see anything in the traceback about tablib or django-import-export.

**Comment by kegan** [comment]
The reason I suspect it was due to `tablib` is because `pip-compile` generates `requirements.txt` with this entry `backports.csv==1.0.7      # via tablib` with `tablib==0.13.0`.

With `tablib==0.14.0`, `backports.csv` is no longer in `requirements.txt`. And the error start appearing.

Then, if I manually install `backports.csv` with `pip install backports.csv`, the error is gone.

Maybe I can create and share a skeleton Django project to show the error in more details.

**Comment by claudep** [comment]
Again, `backports.csv` should NOT be in requirements with Python 3. Sorry, but I'm still not understanding your issue.

**Comment by hugovk** [comment]
Don't know if it's related, but this `Pipfile` looks out of date, shall we remove it? (See PR https://github.com/jazzband/tablib/pull/436.)

https://github.com/jazzband/tablib/blob/5ff4a55ae6fb8a6f9d9d5d8ffeb2c5b8ffa51c85/docs/Pipfile#L9
