### ISSUE TITLE
RST - field with one or more space(s) in a string raises ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by nexone** [jazzband/tablib#469]
Dataset.get_rst raises exception if there's a field with one or more space(s) in a string:
The background is actually that I wanted to create an empty row, but rst apparently ignored a line with only "" and so I came across this error.

Python 3.6.6
tablib v2.0.0

```
import tablib
recs = [
  {"name": "john", "desc":"some guy"},
  {"name": "mary", "desc": " "},  # note a space in desc
]
t = tablib.Dataset()
t.dict = recs
t.get_rst()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\tablib\core.py", line 240, in _get_in_format
    return registry.get_format(fmt_key).export_set(self, **kwargs)
  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\tablib\formats\_rst.py", line 244, in export_set
    column_widths = cls._get_column_widths(dataset, max_table_width)
  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\tablib\formats\_rst.py", line 94, in _get_column_widths
    str_lens, word_lens = cls._get_column_string_lengths(dataset)
  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\tablib\formats\_rst.py", line 53, in _get_column_string_lengths
    word_lens[i] = max(word_lens[i], _max_word_len(text))
  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\tablib\formats\_rst.py", line 27, in _max_word_len
    return max(len(word) for word in text.split()) if text else 0
ValueError: max() arg is an empty sequence
```

**Comment by claudep** [comment]
Many thanks for the report. You might check if the pull request linked above fixes the issue for you.

**Comment by nexone** [comment]
Thanks, problem solved.
Unfortunately, RST still cuts off the spaced line.

**Comment by claudep** [comment]
You might open a new issue about the entire blank line, with example data.
